[workspace]
resolver = "3"
members = [
    "experiments/mini-tree-command",
    "experiments/mini-ls-application",
    "experiments/zenoh-chat-abel",
    "experiments/zenoh-ping-pong/ping",
    "experiments/zenoh-ping-pong/pong",
    "src/bot_framework",
    "src/zenoh_router",
    "src/ping",
    "src/pong",
    "src/a2a",
    "src/agent_a",
    "src/agent_b",
    "src/zenoh_client_launcher/src-tauri"
]